Auto-deploy fixes

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -89,6 +89,7 @@ jobs:
           DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
           DEPLOY_REMOTE_BINARY: ${{ secrets.DEPLOY_REMOTE_BINARY }}
         run: |
+          set -Eeuo pipefail
           chmod 0755 artifact/bot_starter_kit
 
           REMOTE="${DEPLOY_USER}@${DEPLOY_HOST}"
@@ -120,15 +121,18 @@ jobs:
           # nohup and detached standard streams allow the process to survive
           # after the SSH connection closes.
           ssh "${SSH_OPTIONS[@]}" "$REMOTE" \
-            "set -x; \
+            "echo '==>' execute 'set -x;' to debug these commands; \
              echo '### Shutting down the remote service:'; \
              pkill '.*/[t]elegram_bot_rust_starter_kit'; \
              for i in {1..10}; do pgrep '.*/[t]elegram_bot_rust_starter_kit' && sleep 5 || break; done; \
              mv '${DEPLOY_REMOTE_BINARY}~' '${DEPLOY_REMOTE_BINARY}'; \
              echo '### Restarting:'; \
              chmod 0755 '$DEPLOY_REMOTE_BINARY' && \
-             setsid -f '${DEPLOY_REMOTE_BINARY}' </dev/null &>/tmp/log.log \
-             sleep 5; head /tmp/log.log"
+             setsid -f '${DEPLOY_REMOTE_BINARY}' </dev/null &>/tmp/log.log && \
+             sleep 5 && \
+             echo '### Log excerpt:' && \
+             head /tmp/log.log || \
+             echo '*** RESTARTING FAILED'"
 
       - name: Remove SSH private key
         if: always()
